#!/bin/bash

filename="$HOME/.inventory"

if [ ! -f "$filename" ]; then
  touch "$filename"
fi

case "$1" in
  add)
    read -r -p "Container: " container
    if [ -z "$container" ]; then
      echo "Container cannot be empty"
      exit 1
    fi

    while true; do
      read -r -p "Item: " item
      if [ -z "$item" ]; then
        break
      fi

      read -r -p "Quantity: " quantity
      if [ -z "$quantity" ]; then
        quantity=1
      fi

      echo "$container	$quantity	$item" >> "$filename"
    done
    ;;
  containers)
    cut -f1 "$filename" | sort | uniq -c
    ;;
  search)
    fzf < "$filename"
    ;;
  count)
    wc -l < "$filename"
    ;;
  show)
    cut -f1 "$filename" | sort | uniq | while read -r container; do
      echo "$container"
      grep "^$container	" "$filename" | cut -f3 | sort | uniq -c | while read -r line; do
        echo "  $line"
      done
    done
    ;;
  edit)
    $EDITOR "$filename"
    ;;
  *)
    echo "Usage: people <command>"
    echo "Commands:"
    echo "  add - Add an item to the inventory"
    echo "  containers - List all containers"
    echo "  search - Search the inventory"
    echo "  count - Count the number of items in the inventory"
    echo "  show - Show the inventory"
    echo "  edit - Edit the inventory"
    exit 1
    ;;
esac
